# Generated by Django 5.0.2 on 2024-02-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('gender', models.CharField(max_length=16, verbose_name='Пол')),
                ('username', models.CharField(max_length=128, verbose_name='Ник донора для фоток')),
                ('api_id', models.CharField(max_length=32, verbose_name='ID из инструментов разработчика')),
                ('api_hash', models.CharField(max_length=64, verbose_name='Hash из инструментов разработчика')),
            ],
        ),
        migrations.CreateModel(
            name='WaveTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(default=30, verbose_name='Сколько минимально должно пройти времени для того, чтобы подписался еще один чловек в первой волне')),
                ('second', models.IntegerField(default=60, verbose_name='Сколько минимально должно пройти времени для того, чтобы подписался еще один человек во второй волне')),
                ('third', models.IntegerField(default=120, verbose_name='Сколько минимально должно пройти времени для того, чтобы подписался еще один человек в третьей волне')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='Url')),
                ('number_wave', models.IntegerField(default=0, verbose_name='Номер волны подписок')),
                ('gender', models.CharField(max_length=4, verbose_name='Пол исполнителя')),
                ('subscribe', models.PositiveIntegerField(default=0, verbose_name='Сколько подписалось')),
                ('next_action_time', models.DateTimeField(blank=True, null=True, verbose_name='Время Следующего действия')),
                ('start', models.DateTimeField(verbose_name='Дата начала исполнения заказа')),
                ('end', models.DateTimeField(verbose_name='Дата окончания выполнения заказа')),
                ('apis', models.ManyToManyField(to='app.api', verbose_name='Исполнители заказа')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64, null=True, verbose_name='Ник пользователя')),
                ('tg_id', models.CharField(max_length=64, verbose_name='Id пользователя в телеграмме')),
                ('action', models.CharField(default='', max_length=128, null=True, verbose_name='Действия пользхователя')),
                ('create_order', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Поля для создания ордера')),
                ('orders', models.ManyToManyField(to='app.orders', verbose_name='Заказы пользователя')),
            ],
        ),
    ]
